# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
r"""
Regression harness for the data-side gel densitometry scripts. Reads as the
pipeline's handoff contract: for each script, in pipeline order, it states the
inputs that must already exist, the command to run, the outputs that must appear,
the checks JSON that must carry no failed hard check, and the few named golden
values that must not move silently. Nothing here imports pipeline code; every
stage is driven through its command line and observed only through the files it
leaves and its exit code, exactly as the stages hand off to each other in
production. That is deliberate: it is what lets a script be renamed, split, or
reorganized without rewriting the test, and it is what makes a red result mean
"a handoff or a number changed", never "the harness reached inside and broke".

How this is meant to be used (it is a signal, not a gate): run it before stepping
away and after coming back or finishing a reorganization. A red result has exactly
two honest resolutions and no third. Either the pipeline regressed, and you fix it;
or you changed a contract on purpose, and you re-bless it with --update and record
why in the commit. The illegal move is silencing an assertion without a note; the
first time that happens the harness starts to lie. --update never runs by default,
prints every value it (re)captures with a diff against the prior golden, and
refuses to capture a value that is not reproducible across two back-to-back runs,
so re-blessing is always a visible, deliberate act rather than a green button.

Three artifacts, three different lifecycles:
  tests/fixtures/            hand-authored seed inputs. NEVER regenerated by this
                             harness; --update does not touch them. They change
                             only when you edit them by hand, deliberately.
  tests/golden_values.json   captured numbers, keyed by (step, named cell). Written
                             on the first --update run, re-blessed by later --update
                             runs. Carries a hash of the seed fixtures it was
                             captured against, so a fixture edit is diagnosed by its
                             cause ("fixtures changed since goldens captured") rather
                             than as a scatter of value mismatches.
  this file                  the contract. One block per stage; a reorganization of
                             any stage is an edit to that one block.

The serve stage is exercised with NO --tiff and no sibling .tif beside the fixture,
which is the no-crop path: the server serves, POST /extract shells the same
extract_lane_values.py the command line uses, and the written CSV is compared to the
command-line region run. No image is read anywhere in this harness.

Stdlib only. Flat and procedural; emit_message / die / record_check are the only
helpers, duplicated verbatim into each script per the house convention.

Run:
    python3 tests/run_pipeline_tests.py                 (check against goldens)
    python3 tests/run_pipeline_tests.py --update        (re-capture goldens)
"""

import argparse
import csv
import datetime
import hashlib
import json
import pathlib
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request

# =============================================================================
# Configuration. Every value that is not derived is named here with its unit or
# meaning, per the house rule that a bare literal in the body is a defect.
# =============================================================================

# The interpreter used to invoke every stage. sys.executable rather than a bare
# "python3" so the subprocesses run under the exact interpreter running the
# harness (matters under uv, a venv, or a non-default python3 on PATH). The
# scripts carry uv inline dependency blocks, but their non-stdlib dependencies
# (numpy, scipy, matplotlib) are assumed already importable by this interpreter;
# invoking through "uv run" instead would re-resolve them per stage and can reach
# the network, which is not wanted in a test.
STAGE_INTERPRETER = sys.executable

# The pipeline scripts live one directory up from this tests/ directory.
TESTS_DIRECTORY = pathlib.Path(__file__).resolve().parent
REPOSITORY_ROOT_DIRECTORY = TESTS_DIRECTORY.parent
FIXTURES_DIRECTORY = TESTS_DIRECTORY / "fixtures"
GOLDEN_VALUES_PATH = TESTS_DIRECTORY / "golden_values.json"

# The fixture gel directory name must end in this suffix and match the TIFF stem,
# because analyze_gel derives gel_id from the directory name and serve_gel_picker
# derives the expected TIFF filename from it. A wrongly named fixture dir would
# silently change gel_id (a real difference we saw while designing this), so the
# name is pinned here and asserted, not assumed.
GEL_ANALYSIS_DIRECTORY_SUFFIX = "_gel_analysis"
FIXTURE_GEL_DIRECTORY_NAME = (
    "20260818_rotated_LM-0008_s0012_SDSPAGE_run-old-MCM-aliquots_Fl-Green_gel_analysis"
)
FIXTURE_MANIFEST_FILENAME = "manifest.csv"

# The region window and band index the harness extracts. These choose which
# per-lane numbers become goldens; they are named here so a change to the tested
# selection is a one-line edit rather than scattered literals. The region matches
# the shipped extract_region_31.3-46.1mm_none.csv, the one hand-checked good run.
REGION_START_MILLIMETRES = 31.3
REGION_END_MILLIMETRES = 46.1
REGION_NET_BASELINE = "none"
BAND_INDEX = 1
BAND_QUANTITY = "area"

# The selector string both plot and aggregate key their filenames on. Derived from
# the region selection exactly as the extractor builds its output stem
# (extract_region_%g-%gmm_%s), so the downstream single_experiment_<selector> and
# aggregate_<selector> files line up. plot and aggregate are addressed with this
# selector EXPLICITLY (--extract-csv, --selector) rather than by auto-find: with
# both an extract_region_* and an extract_band_* file present, plot's auto-find is
# ambiguous and exits, which we confirmed by running it.
REGION_SELECTOR = "region_%g-%gmm_%s" % (
    REGION_START_MILLIMETRES,
    REGION_END_MILLIMETRES,
    REGION_NET_BASELINE,
)

# Golden comparison tolerance. The region values are integer-valued signal sums up
# to ~1.6e8 written as floats ("162056329.0"), so a tight relative tolerance is
# safe for them; the per-key overrides below exist for any value that legitimately
# carries more numerical noise. A default this tight means a real regression cannot
# hide inside the tolerance, while float-formatting drift (the trailing ".0") is
# still absorbed because it compares equal.
DEFAULT_RELATIVE_TOLERANCE = 1e-6
GOLDEN_RELATIVE_TOLERANCE_OVERRIDES = {
    # key: relative_tolerance   (add entries only with a recorded reason)
}

# Serve stage. A fixed high port rather than an OS-assigned one because
# serve_gel_picker takes --port and does not report back a chosen port; the small
# retry range below handles the port being momentarily busy.
SERVE_BASE_PORT = 8734
SERVE_PORT_RETRY_COUNT = 8
SERVE_READINESS_POLL_COUNT = 60
SERVE_READINESS_POLL_SECONDS = 0.1
SERVE_REQUEST_TIMEOUT_SECONDS = 15
SERVE_SHUTDOWN_JOIN_SECONDS = 5

ACCUMULATED_RUN_LOG_LINES = []


def emit_message(source_tag, message_text):
    timestamp_text = datetime.datetime.now().astimezone().isoformat(timespec="seconds")
    tagged_line = "[" + source_tag + "] " + message_text
    ACCUMULATED_RUN_LOG_LINES.append(timestamp_text + " " + tagged_line)
    print(tagged_line, file=sys.stderr)


def die(source_tag, message_text):
    emit_message(source_tag, "ERROR: " + message_text)
    sys.exit(1)


# record_check here plays the same role it plays in the pipeline scripts: it
# appends a verdict and, unlike the pipeline version, never writes a checks file
# (the harness's durable artifact is its stderr log and its exit code). Kept as the
# third permitted helper so the harness reads like the scripts it tests.
accumulated_check_records = []


def record_check(check_name, severity, passed, detail_text):
    accumulated_check_records.append(
        {
            "check": check_name,
            "severity": severity,
            "passed": bool(passed),
            "detail": detail_text,
        }
    )


# =============================================================================
# Arguments
# =============================================================================

argument_parser = argparse.ArgumentParser(
    prog="run_pipeline_tests.py",
    description="Regression harness for the data-side gel pipeline scripts.",
    allow_abbrev=False,
)
argument_parser.add_argument(
    "--update",
    action="store_true",
    dest="update_goldens",
    help="re-capture golden values from this run instead of comparing against them",
)
parsed_arguments = argument_parser.parse_args()
updating_goldens = parsed_arguments.update_goldens

# =============================================================================
# Shared helpers used by the step blocks below. These are inlined-once utilities
# in spirit, but each is used at every one of the seven step blocks, so by the
# house rule ("add abstraction when the second real call site exists") they are
# real shared helpers, not speculative ones. Kept tiny and side-effect-free.
# =============================================================================


def read_named_cell(csv_path, match_column, match_value, value_column):
    # Pull one cell: the value_column of the row whose match_column equals
    # match_value (compared as integers, which every lane/band key in these CSVs
    # is). utf-8-sig strips the Excel BOM and cells are trimmed, matching how every
    # pipeline script reads its CSVs, so a hand-exported file cannot break the
    # match invisibly.
    with csv_path.open(newline="", encoding="utf-8-sig") as csv_handle:
        for raw_row in csv.DictReader(csv_handle):
            trimmed_row = {
                column_name: (cell.strip() if isinstance(cell, str) else cell)
                for column_name, cell in raw_row.items()
            }
            if int(trimmed_row[match_column]) == match_value:
                return trimmed_row[value_column]
    return None


def read_named_cell_two_keys(
    csv_path, first_column, first_value, second_column, second_value, value_column
):
    # As read_named_cell but keyed on two integer columns (lane_index plus
    # canonical_band_index in band_measurements, where a lane carries many bands).
    with csv_path.open(newline="", encoding="utf-8-sig") as csv_handle:
        for raw_row in csv.DictReader(csv_handle):
            trimmed_row = {
                column_name: (cell.strip() if isinstance(cell, str) else cell)
                for column_name, cell in raw_row.items()
            }
            if (
                int(trimmed_row[first_column]) == first_value
                and int(trimmed_row[second_column]) == second_value
            ):
                return trimmed_row[value_column]
    return None


def checks_json_has_failed_hard_check(checks_json_path):
    # The uniform contract across every pipeline script: a top-level "checks" array
    # whose records carry severity ("hard"/"soft") and passed (bool). A failed hard
    # check invalidates the stage's output. Returns (has_failure, detail_text).
    checks_report = json.loads(checks_json_path.read_text(encoding="utf-8-sig"))
    for check_record in checks_report.get("checks", []):
        if check_record.get("severity") == "hard" and not check_record.get("passed"):
            return True, check_record.get("check", "unnamed hard check")
    return False, ""


def golden_relative_difference(observed_text, golden_value):
    # Compare a freshly produced cell (a string read from a CSV) against a stored
    # golden number by relative difference, so float formatting like "162056329.0"
    # vs 162056329 compares equal. Returns the relative difference as a float.
    observed_value = float(observed_text)
    golden_number = float(golden_value)
    if golden_number == 0.0:
        return abs(observed_value)
    return abs(observed_value - golden_number) / abs(golden_number)


# =============================================================================
# Fixture staging. Copy the seed fixture gel directory into a fresh temporary
# working tree every run, so stale outputs from a prior run can never mask a
# regression, and so the read-only fixtures are never written to. The manifest is
# copied alongside the gel directory, preserving the "manifest one level above the
# gel dir, relative analysis_path" layout the manifest and aggregator resolve.
# =============================================================================

if not FIXTURES_DIRECTORY.is_dir():
    die("fixtures", "fixtures directory not found: " + str(FIXTURES_DIRECTORY))

seed_gel_directory = FIXTURES_DIRECTORY / FIXTURE_GEL_DIRECTORY_NAME
seed_manifest_path = FIXTURES_DIRECTORY / FIXTURE_MANIFEST_FILENAME
if not seed_gel_directory.is_dir():
    die("fixtures", "seed gel directory not found: " + str(seed_gel_directory))
if not seed_manifest_path.is_file():
    die("fixtures", "seed manifest not found: " + str(seed_manifest_path))

# The gel directory name must end in the analysis suffix, because analyze_gel and
# serve derive gel_id and the expected TIFF stem from it. Asserted, not assumed.
if not seed_gel_directory.name.endswith(GEL_ANALYSIS_DIRECTORY_SUFFIX):
    die(
        "fixtures",
        "fixture gel directory name must end in '"
        + GEL_ANALYSIS_DIRECTORY_SUFFIX
        + "': "
        + seed_gel_directory.name,
    )

# Hash the seed fixtures (their bytes, in sorted path order) so the goldens can
# record which inputs they were captured against. A later run whose fixtures no
# longer hash to this value is told so by cause, before any value comparison, so a
# hand edit to a seed CSV is not misread as a code regression.
fixture_hash_accumulator = hashlib.sha256()
for seed_file_path in sorted(FIXTURES_DIRECTORY.rglob("*")):
    if seed_file_path.is_file():
        relative_name = seed_file_path.relative_to(FIXTURES_DIRECTORY).as_posix()
        fixture_hash_accumulator.update(relative_name.encode("utf-8"))
        fixture_hash_accumulator.update(seed_file_path.read_bytes())
seed_fixtures_hash = fixture_hash_accumulator.hexdigest()

working_root_directory = pathlib.Path(
    tempfile.mkdtemp(prefix="gel_pipeline_regression_")
)
working_gel_directory = working_root_directory / FIXTURE_GEL_DIRECTORY_NAME
shutil.copytree(seed_gel_directory, working_gel_directory)
shutil.copy2(seed_manifest_path, working_root_directory / FIXTURE_MANIFEST_FILENAME)
working_manifest_path = working_root_directory / FIXTURE_MANIFEST_FILENAME
emit_message("fixtures", "staged working tree at " + str(working_root_directory))

# Guard the serve no-crop path: there must be no .tif matching the gel stem beside
# the working gel directory, or serve would rasterise a crop and read an image. The
# temp tree contains only CSVs, so this holds; asserted so a future fixture that
# ships a TIFF cannot silently turn the image path on inside a test.
gel_stem = FIXTURE_GEL_DIRECTORY_NAME[: -len(GEL_ANALYSIS_DIRECTORY_SUFFIX)]
for search_directory in (working_gel_directory, working_root_directory):
    for found_tiff in search_directory.glob("*.tif"):
        if gel_stem in found_tiff.name:
            die(
                "fixtures",
                "a TIFF matching the gel stem is present ("
                + str(found_tiff)
                + "); the serve stage must run the no-crop path with no image read",
            )

# Load the prior goldens (for comparison) or start an empty capture (for --update).
if updating_goldens:
    captured_goldens = {}
    prior_goldens = {}
    if GOLDEN_VALUES_PATH.is_file():
        prior_goldens = json.loads(
            GOLDEN_VALUES_PATH.read_text(encoding="utf-8-sig")
        ).get("goldens", {})
    emit_message("golden", "--update: re-capturing goldens from this run")
else:
    if not GOLDEN_VALUES_PATH.is_file():
        die(
            "golden",
            "no golden_values.json; run once with --update to capture goldens first",
        )
    golden_document = json.loads(GOLDEN_VALUES_PATH.read_text(encoding="utf-8-sig"))
    stored_goldens = golden_document.get("goldens", {})
    stored_fixture_hash = golden_document.get("seed_fixtures_hash")
    # Diagnose a fixture/golden mismatch by cause, before any value comparison, so
    # an intentional seed edit reads as one clear message rather than many value
    # failures. Not fatal: the run continues and the value checks will show what
    # moved, but the operator is told the likely reason first.
    if stored_fixture_hash is not None and stored_fixture_hash != seed_fixtures_hash:
        emit_message(
            "golden",
            "WARNING fixtures changed since goldens captured ("
            + str(stored_fixture_hash)[:12]
            + " -> "
            + seed_fixtures_hash[:12]
            + "); re-run --update if this fixture change was intended",
        )

# Records the per-step outcome lines and whether any step failed.
step_outcome_lines = []
any_step_failed = False


def evaluate_golden(step_name, golden_key, observed_text):
    # Compare-or-capture one golden. In --update mode, capture the observed value and
    # print a diff versus the prior value so a re-bless is always visible. In compare
    # mode, measure the relative difference against the stored golden and return
    # whether it is within tolerance, with a detail string for the outcome line.
    #
    # Goldens are only ever placed on cells that are deterministic functions of the
    # seed input (integer signal sums, blank-corrected values, group means), never on
    # provenance fields such as gel_id (which is derived from the directory name) or
    # the generated_at timestamps, so a captured value is reproducible run to run.
    # This was verified directly while building the harness: numeric outputs of
    # analyze_gel were byte-identical across independent runs. A per-update
    # double-run guard was considered and rejected as defense the evidence does not
    # require; if a future golden is placed on a noisier cell, run --update twice and
    # confirm the captured value is stable before trusting it.
    fully_qualified_key = step_name + "." + golden_key
    tolerance = GOLDEN_RELATIVE_TOLERANCE_OVERRIDES.get(
        fully_qualified_key, DEFAULT_RELATIVE_TOLERANCE
    )
    if updating_goldens:
        captured_goldens.setdefault(step_name, {})[golden_key] = observed_text
        prior_value = prior_goldens.get(step_name, {}).get(golden_key)
        if prior_value is None:
            emit_message(
                "golden", "capture " + fully_qualified_key + " = " + str(observed_text)
            )
        elif str(prior_value) != str(observed_text):
            relative_difference = golden_relative_difference(observed_text, prior_value)
            emit_message(
                "golden",
                "re-bless "
                + fully_qualified_key
                + ": "
                + str(prior_value)
                + " -> "
                + str(observed_text)
                + " (rel %.3e)" % relative_difference,
            )
        return True, "captured"
    golden_value = stored_goldens.get(step_name, {}).get(golden_key)
    if golden_value is None:
        return False, "golden " + fully_qualified_key + " absent; run --update"
    relative_difference = golden_relative_difference(observed_text, golden_value)
    within_tolerance = relative_difference <= tolerance
    detail_text = "%s: %s vs golden %s (rel %.3e, tol %.0e)" % (
        golden_key,
        observed_text,
        golden_value,
        relative_difference,
        tolerance,
    )
    return within_tolerance, detail_text


def run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    checks_json_file,
):
    # Assert one stage's boundary contract, in the order a failure is most cheaply
    # diagnosed: prerequisites (is the stage wired to inputs that exist), exit code,
    # products (did it leave what the next stage needs), and the hard-check gate.
    # Returns (contract_passed, detail_text) so the caller can then layer on the
    # stage's golden-value checks. Prerequisite failures are tagged distinctly from
    # product failures because they mean different things: a missing prerequisite is
    # usually a fixture or wiring problem, a missing product is a stage regression.
    for required_input_file in required_input_files:
        if not required_input_file.is_file():
            return False, "prerequisite missing: " + required_input_file.name
    completed_process = subprocess.run(
        stage_command, capture_output=True, text=True
    )
    if completed_process.returncode != 0:
        last_stderr_line = ""
        if completed_process.stderr.strip():
            last_stderr_line = completed_process.stderr.strip().splitlines()[-1]
        return False, "exit %d: %s" % (completed_process.returncode, last_stderr_line)
    for expected_output_file in expected_output_files:
        if not expected_output_file.is_file():
            return False, "product missing: " + expected_output_file.name
    if checks_json_file is not None:
        has_hard_failure, failed_check_name = checks_json_has_failed_hard_check(
            checks_json_file
        )
        if has_hard_failure:
            return False, "failed hard check: " + failed_check_name
    return True, "contract ok"


def register_step_outcome(step_name, passed, detail_text):
    # One line per step to stderr, self-triaging: the detail says whether a failure
    # was a wiring break (prerequisite/product/exit) or a numbers change (golden),
    # so the reader knows how to respond without opening the code.
    global any_step_failed
    verdict = "PASS" if passed else "FAIL"
    outcome_line = "%-4s %-22s %s" % (verdict, step_name, detail_text)
    step_outcome_lines.append((step_name, passed, outcome_line))
    emit_message("step", outcome_line)
    if not passed:
        any_step_failed = True


# =============================================================================
# PIPELINE ORDER. The stages, as data, in the order they run and hand off. This is
# the affordance chain: reading it top to bottom is reading what the pipeline does.
# Reordering or inserting a stage is an edit here plus the stage's own block below.
# =============================================================================
#
#   1. validate_sample_sheet   gate the sheet against the profiles
#   2. analyze_gel             detrend, detect bands, measure -> band_measurements
#   3. extract_lane_values     region mode  -> extract_region_<sel>.csv
#   4. extract_lane_values     band mode    -> extract_band_<N>_<q>.csv
#   5. plot_single_experiment  blank-correct -> single_experiment_<sel>.csv
#   6. validate_manifest       gate the replicate manifest
#   7. aggregate_repeats       stack replicates -> aggregate_<sel>.csv
#   8. serve_gel_picker        no-crop serve; POST /extract equals the CLI region
#
# =============================================================================

# -----------------------------------------------------------------------------
# STEP 1: validate_sample_sheet
# Reorganizing this stage: edit the command, prerequisites, products, and checks
# filename below. It consumes the two seed CSVs and writes sample_sheet_checks.json.
# -----------------------------------------------------------------------------
step_name = "validate_sample_sheet"
stage_command = [
    STAGE_INTERPRETER,
    str(REPOSITORY_ROOT_DIRECTORY / "validate_sample_sheet.py"),
    str(working_gel_directory),
]
required_input_files = [
    working_gel_directory / "manual_lane_profiles.csv",
    working_gel_directory / "sample_sheet.csv",
]
checks_json_file = working_gel_directory / "sample_sheet_checks.json"
expected_output_files = [checks_json_file]
contract_passed, contract_detail = run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    checks_json_file,
)
register_step_outcome(step_name, contract_passed, contract_detail)

# -----------------------------------------------------------------------------
# STEP 2: analyze_gel
# Reorganizing this stage (e.g. regions moved to ImageJ, analysis -> QC/metrics):
# its PRODUCTS may change while its PREREQUISITES (needs the profile export and the
# sheet) mostly do not, so the prerequisite assertion still validates the front of
# the wiring even if the golden below must be re-pointed. gel_id is NOT goldened: it
# is derived from the gel directory name, not computed from data.
# -----------------------------------------------------------------------------
step_name = "analyze_gel"
band_measurements_path = working_gel_directory / "band_measurements.csv"
stage_command = [
    STAGE_INTERPRETER,
    str(REPOSITORY_ROOT_DIRECTORY / "analyze_gel.py"),
    str(working_gel_directory),
]
required_input_files = [
    working_gel_directory / "manual_lane_profiles.csv",
    working_gel_directory / "sample_sheet.csv",
]
checks_json_file = working_gel_directory / "profile_checks.json"
expected_output_files = [
    band_measurements_path,
    working_gel_directory / "consensus_bands.csv",
    checks_json_file,
]
contract_passed, contract_detail = run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    checks_json_file,
)
if contract_passed:
    # Golden: one measured lane's reported_area at a stable, well-supported band.
    analyze_reported_area = read_named_cell_two_keys(
        band_measurements_path,
        "lane_index",
        5,
        "canonical_band_index",
        BAND_INDEX,
        "reported_area",
    )
    if analyze_reported_area is None:
        contract_passed, contract_detail = False, "golden cell not found in band_measurements"
    else:
        contract_passed, contract_detail = evaluate_golden(
            step_name, "lane5_band%d_reported_area" % BAND_INDEX, analyze_reported_area
        )
register_step_outcome(step_name, contract_passed, contract_detail)

# -----------------------------------------------------------------------------
# STEP 3: extract_lane_values, region mode. The golden anchor: this is the run that
# reproduces the shipped extract_region_31.3-46.1mm_none.csv, hand-checked good.
# Reorganizing region definition (a picker drag today, perhaps an ImageJ ROI file
# later) changes the command and possibly adds a prerequisite file; the products
# and goldens stay keyed on the region selector.
# -----------------------------------------------------------------------------
step_name = "extract_region"
extract_region_csv_path = working_gel_directory / (
    "extract_region_%g-%gmm_%s.csv"
    % (REGION_START_MILLIMETRES, REGION_END_MILLIMETRES, REGION_NET_BASELINE)
)
stage_command = [
    STAGE_INTERPRETER,
    str(REPOSITORY_ROOT_DIRECTORY / "extract_lane_values.py"),
    str(working_gel_directory),
    "--region",
    "%g" % REGION_START_MILLIMETRES,
    "%g" % REGION_END_MILLIMETRES,
    "--net-baseline",
    REGION_NET_BASELINE,
]
required_input_files = [
    working_gel_directory / "manual_lane_profiles.csv",
    band_measurements_path,
]
checks_json_file = working_gel_directory / (
    "extract_region_%g-%gmm_%s_checks.json"
    % (REGION_START_MILLIMETRES, REGION_END_MILLIMETRES, REGION_NET_BASELINE)
)
expected_output_files = [extract_region_csv_path, checks_json_file]
contract_passed, contract_detail = run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    checks_json_file,
)
if contract_passed:
    # Two goldens: the reference lane and a high-signal sample lane, both integer
    # signal sums where a real regression cannot hide inside the tolerance.
    for golden_lane_index, golden_key in ((6, "lane6_value"), (7, "lane7_value")):
        observed_value = read_named_cell(
            extract_region_csv_path, "lane_index", golden_lane_index, "value"
        )
        if observed_value is None:
            contract_passed, contract_detail = False, "golden lane %d not found" % golden_lane_index
            break
        golden_passed, golden_detail = evaluate_golden(
            step_name, golden_key, observed_value
        )
        if not golden_passed:
            contract_passed, contract_detail = False, golden_detail
            break
        contract_detail = golden_detail
register_step_outcome(step_name, contract_passed, contract_detail)

# -----------------------------------------------------------------------------
# STEP 4: extract_lane_values, band mode. Produces the second extract file, which is
# also what makes plot's auto-find ambiguous downstream (hence STEP 5 passes
# --extract-csv explicitly). Reorganizing: same as STEP 3 but keyed on the band.
# -----------------------------------------------------------------------------
step_name = "extract_band"
extract_band_csv_path = working_gel_directory / (
    "extract_band_%d_%s.csv" % (BAND_INDEX, BAND_QUANTITY)
)
stage_command = [
    STAGE_INTERPRETER,
    str(REPOSITORY_ROOT_DIRECTORY / "extract_lane_values.py"),
    str(working_gel_directory),
    "--band",
    str(BAND_INDEX),
    "--quantity",
    BAND_QUANTITY,
]
required_input_files = [band_measurements_path]
checks_json_file = working_gel_directory / (
    "extract_band_%d_%s_checks.json" % (BAND_INDEX, BAND_QUANTITY)
)
expected_output_files = [extract_band_csv_path, checks_json_file]
contract_passed, contract_detail = run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    checks_json_file,
)
if contract_passed:
    # Golden: the reference lane's per-band value.
    observed_value = read_named_cell(
        extract_band_csv_path, "lane_index", 6, "value"
    )
    if observed_value is None:
        contract_passed, contract_detail = False, "golden lane 6 not found"
    else:
        contract_passed, contract_detail = evaluate_golden(
            step_name, "lane6_value", observed_value
        )
register_step_outcome(step_name, contract_passed, contract_detail)

# -----------------------------------------------------------------------------
# STEP 5: plot_single_experiment. Blank-corrects the region extract into per-sample
# value_corrected. --extract-csv is passed EXPLICITLY: with both an extract_region_*
# and an extract_band_* file present (STEP 3 and STEP 4), the auto-find is ambiguous
# and the stage exits. The .png product is asserted to EXIST but is never opened.
# -----------------------------------------------------------------------------
step_name = "plot_single_experiment"
single_experiment_csv_path = working_gel_directory / (
    "single_experiment_%s.csv" % REGION_SELECTOR
)
stage_command = [
    STAGE_INTERPRETER,
    str(REPOSITORY_ROOT_DIRECTORY / "plot_single_experiment.py"),
    str(working_gel_directory),
    "--extract-csv",
    str(extract_region_csv_path),
]
required_input_files = [
    extract_region_csv_path,
    working_gel_directory / "sample_sheet.csv",
]
checks_json_file = working_gel_directory / (
    "single_experiment_%s_checks.json" % REGION_SELECTOR
)
expected_output_files = [
    single_experiment_csv_path,
    working_gel_directory / ("single_experiment_%s.png" % REGION_SELECTOR),
    checks_json_file,
]
contract_passed, contract_detail = run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    checks_json_file,
)
if contract_passed:
    # Golden: the reference sample's blank-corrected value.
    observed_value = read_named_cell(
        single_experiment_csv_path, "well_number", 10, "value_corrected"
    )
    if observed_value is None:
        contract_passed, contract_detail = False, "golden sample (well 10) not found"
    else:
        contract_passed, contract_detail = evaluate_golden(
            step_name, "well10_value_corrected", observed_value
        )
register_step_outcome(step_name, contract_passed, contract_detail)

# -----------------------------------------------------------------------------
# STEP 6: validate_manifest. Gates the replicate manifest that sits one level above
# the gel directory. It also writes manifest_template.csv beside the manifest.
# Reorganizing: the manifest schema lives in validate_manifest and aggregate; a
# column change edits both stages' blocks.
# -----------------------------------------------------------------------------
step_name = "validate_manifest"
manifest_checks_path = working_root_directory / "manifest_checks.json"
stage_command = [
    STAGE_INTERPRETER,
    str(REPOSITORY_ROOT_DIRECTORY / "validate_manifest.py"),
    str(working_manifest_path),
]
required_input_files = [working_manifest_path]
expected_output_files = [
    manifest_checks_path,
    working_root_directory / "manifest_template.csv",
]
contract_passed, contract_detail = run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    manifest_checks_path,
)
register_step_outcome(step_name, contract_passed, contract_detail)

# -----------------------------------------------------------------------------
# STEP 7: aggregate_repeats. Stacks the single_experiment values across replicates.
# --selector is pinned so it finds single_experiment_<selector>.csv rather than
# globbing (the gel directory could hold more than one). This single-gel fixture
# gives n=1 groups, so the "every group has at least two replicates" check fires as
# a SOFT warning and correctly does NOT fail the hard-check gate; the mean of an
# n=1 group equals that sample's value_corrected, which is a clean golden.
# To exercise real replicate averaging, add a second analysis_path row to the
# fixture manifest pointing at a second gel directory, and re-bless the mean.
# -----------------------------------------------------------------------------
step_name = "aggregate_repeats"
aggregate_csv_path = working_root_directory / ("aggregate_%s.csv" % REGION_SELECTOR)
stage_command = [
    STAGE_INTERPRETER,
    str(REPOSITORY_ROOT_DIRECTORY / "aggregate_repeats.py"),
    str(working_manifest_path),
    "--selector",
    REGION_SELECTOR,
]
required_input_files = [working_manifest_path, single_experiment_csv_path]
checks_json_file = working_root_directory / ("aggregate_%s_checks.json" % REGION_SELECTOR)
expected_output_files = [
    aggregate_csv_path,
    working_root_directory / ("aggregate_%s.png" % REGION_SELECTOR),
    checks_json_file,
]
contract_passed, contract_detail = run_stage_and_assert_contract(
    step_name,
    stage_command,
    required_input_files,
    expected_output_files,
    checks_json_file,
)
if contract_passed:
    # Golden: one group's mean (n=1, so it equals that sample's value_corrected).
    # sample_label is a string key, not an integer, so read it directly rather than
    # through read_named_cell (which casts keys to int for the lane/band columns).
    observed_value = None
    with aggregate_csv_path.open(newline="", encoding="utf-8-sig") as aggregate_handle:
        observed_value = None
        for aggregate_row in csv.DictReader(aggregate_handle):
            if aggregate_row["sample_label"].strip() == "BK_blue":
                observed_value = aggregate_row["mean"].strip()
                break
    if observed_value is None:
        contract_passed, contract_detail = False, "golden group BK_blue not found"
    else:
        contract_passed, contract_detail = evaluate_golden(
            step_name, "BK_blue_mean", observed_value
        )
register_step_outcome(step_name, contract_passed, contract_detail)

# -----------------------------------------------------------------------------
# STEP 8: serve_gel_picker, no-crop path. Launch with NO --tiff and no sibling
# .tif, so the server serves without reading any image; POST /extract runs the same
# extract_lane_values.py the command line uses; assert the server-written CSV's
# per-lane values equal the command-line region run (STEP 3). Clean teardown via
# POST /shutdown; the process is joined with a timeout and only killed as a last
# resort, so a failure cannot leave a zombie or hang the harness.
# Reorganizing serve (region-picker changes, payload/html changes) touches its
# request shape here, but the CLI-equivalence assertion is unchanged as long as
# /extract still shells the extractor.
# -----------------------------------------------------------------------------
step_name = "serve_gel_picker"
serve_process = None
serve_detail = "contract ok"
serve_passed = True
try:
    # Claim a port from a small range in case the base port is momentarily busy.
    serve_port = None
    for candidate_port in range(SERVE_BASE_PORT, SERVE_BASE_PORT + SERVE_PORT_RETRY_COUNT):
        serve_command = [
            STAGE_INTERPRETER,
            str(REPOSITORY_ROOT_DIRECTORY / "serve_gel_picker.py"),
            str(working_gel_directory),
            "--port",
            str(candidate_port),
        ]
        serve_process = subprocess.Popen(
            serve_command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )
        server_base_url = "http://127.0.0.1:%d" % candidate_port
        server_became_ready = False
        for _poll_attempt in range(SERVE_READINESS_POLL_COUNT):
            if serve_process.poll() is not None:
                # The server exited before becoming ready (likely port in use);
                # break to try the next candidate port.
                break
            try:
                with urllib.request.urlopen(
                    server_base_url + "/payload", timeout=1
                ) as readiness_response:
                    if readiness_response.status == 200:
                        server_became_ready = True
                        break
            except Exception:
                time.sleep(SERVE_READINESS_POLL_SECONDS)
        if server_became_ready:
            serve_port = candidate_port
            break
        # This candidate port did not come up; ensure the process is gone before
        # trying the next one, so we never leak a half-started server.
        if serve_process.poll() is None:
            serve_process.terminate()
        serve_process.wait(timeout=SERVE_SHUTDOWN_JOIN_SECONDS)
        serve_process = None

    if serve_port is None:
        serve_passed, serve_detail = False, "server did not become ready on any port"
    else:
        # POST the same region selection STEP 3 ran on the command line.
        extract_request_body = json.dumps(
            {
                "mode": "region",
                "start_millimetres": REGION_START_MILLIMETRES,
                "end_millimetres": REGION_END_MILLIMETRES,
                "net_baseline": REGION_NET_BASELINE,
            }
        ).encode("utf-8")
        extract_request = urllib.request.Request(
            server_base_url + "/extract",
            data=extract_request_body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(
            extract_request, timeout=SERVE_REQUEST_TIMEOUT_SECONDS
        ) as extract_response:
            extract_result = json.loads(extract_response.read())
        if not extract_result.get("ok"):
            serve_passed, serve_detail = False, "server /extract failed: " + str(
                extract_result.get("error")
            )
        else:
            # Compare the server's returned rows to the command-line region CSV on
            # the per-lane value, the number the pipeline reports. Provenance
            # columns (timestamps etc) are not compared.
            command_line_values_by_lane = {}
            with extract_region_csv_path.open(
                newline="", encoding="utf-8-sig"
            ) as command_line_handle:
                for command_line_row in csv.DictReader(command_line_handle):
                    command_line_values_by_lane[int(command_line_row["lane_index"])] = (
                        command_line_row["value"].strip()
                    )
            server_values_by_lane = {}
            for server_row in extract_result.get("rows", []):
                server_values_by_lane[int(server_row["lane_index"])] = str(
                    server_row["value"]
                ).strip()
            mismatched_lanes = [
                lane_index
                for lane_index in command_line_values_by_lane
                if command_line_values_by_lane[lane_index]
                != server_values_by_lane.get(lane_index)
            ]
            if mismatched_lanes:
                serve_passed, serve_detail = False, "serve vs CLI mismatch at lanes %s" % (
                    mismatched_lanes[:5]
                )
            else:
                serve_detail = "serve /extract equals CLI over %d lanes" % len(
                    command_line_values_by_lane
                )
        # Clean teardown regardless of the assertion outcome above.
        try:
            urllib.request.urlopen(
                urllib.request.Request(
                    server_base_url + "/shutdown", data=b"{}", method="POST"
                ),
                timeout=SERVE_REQUEST_TIMEOUT_SECONDS,
            ).read()
        except Exception:
            pass
finally:
    if serve_process is not None:
        try:
            serve_process.wait(timeout=SERVE_SHUTDOWN_JOIN_SECONDS)
        except subprocess.TimeoutExpired:
            serve_process.kill()
            serve_process.wait(timeout=SERVE_SHUTDOWN_JOIN_SECONDS)
register_step_outcome(step_name, serve_passed, serve_detail)

# =============================================================================
# Persist goldens on --update, then the summary and exit code. The goldens file is
# written only after all steps ran, so a mid-run failure never leaves a half-written
# golden set. On a non-update run the file is untouched.
# =============================================================================

if updating_goldens:
    GOLDEN_VALUES_PATH.write_text(
        json.dumps(
            {
                "schema_version": "gel_pipeline_regression_goldens_1",
                "generated_at": datetime.datetime.now()
                .astimezone()
                .isoformat(timespec="seconds"),
                "seed_fixtures_hash": seed_fixtures_hash,
                "default_relative_tolerance": DEFAULT_RELATIVE_TOLERANCE,
                "goldens": captured_goldens,
            },
            indent=2,
        )
        + "\n"
    )
    emit_message("golden", "wrote " + str(GOLDEN_VALUES_PATH))

# Leave the staged working tree in place only on failure, so a red run can be
# inspected; clean it up on success to avoid accumulating temp trees.
if any_step_failed:
    emit_message(
        "summary",
        "working tree left for inspection at " + str(working_root_directory),
    )
else:
    shutil.rmtree(working_root_directory, ignore_errors=True)

passed_step_count = sum(1 for _name, passed, _line in step_outcome_lines if passed)
emit_message(
    "summary",
    "%d of %d steps passed%s"
    % (
        passed_step_count,
        len(step_outcome_lines),
        " (goldens updated)" if updating_goldens else "",
    ),
)
sys.exit(1 if any_step_failed else 0)
